[module]
  [[module.imports]]
    path = 'github.com/LordMathis/hugo-theme-nightfall'
  [module.hugoVersion]
    min = "0.114.0"
    theme = "nightfall"

[params]
user = "jrecheverria"
hostname = "rubenecheverria.dev"
sitedescription = 'Your website description'
  [params.author]
    name = "Ruben Echeverria"
    email = "javier.ruben.echeverria@gmail.com"



[[params.social]]
key = 0
name = "github"
url = "https://github.com/jrecheverria"

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.linkedin.com/in/ruben-echeverria-780617195/"


[[params.social]]
key = 3
name = "email"
url = "javier.ruben.echeverria@gmail.com"

[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about/"
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"

